project_id = "quwwtoinxeaiwsojfrfy"

[functions.create-checkout]
verify_jwt = false

[functions.create-checkout-paypal]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.secure-download]
verify_jwt = false

[functions.download-file]
verify_jwt = false

[functions.sync-preview-video]
verify_jwt = false

[functions.admin-download]
verify_jwt = false
