project_id = "quwwtoinxeaiwsojfrfy"

[functions.create-checkout]
verify_jwt = false

[functions.mp-webhook]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.secure-download]
verify_jwt = false
